### ISSUE TITLE
open v camelot

### ISSUE THREAD

**Issue by starchild** [kokernutz/traktor-kontrol-screens#10]
i find it confusing now when my laptop is showing open key, but the S8 display is showing camelot now.

Can we make the S8 show open key instead, or have an option to do so somehow please?

**Comment by starchild** [comment]
awesome :)

**Comment by kokernutz** [comment]
I pushed out an update this morning which lets you toggle Camelot key via the prefs file.

**Comment by starchild** [comment]
Awesome, thanks a lot!
