### ISSUE TITLE
no key offset showing in browse mode

### ISSUE THREAD

**Issue by starchild** [kokernutz/traktor-kontrol-screens#2]
I'm on mac sierra, and I see no key offset for valid file matches.  Was this feature removed?

It would be great to add colour ranges back for high/mid/low if possible please.

Great job otherwise.  Thanks.

**Comment by skymakai** [comment]
@starchild 
It works by taking the current key from the 'Master' track.  That means you have to be playing a track in a deck, and have it set as the Tempo Master.  Then, you should see available matches and the key offset info in the Browser.

**Comment by starchild** [comment]
master tempo - gotcha, thanks.

what about colour ranges?

**Comment by skymakai** [comment]
@starchild 
Do you mean a color wave form?
@kokernutz 
I'd also like the color wave form enabled.

**Comment by skymakai** [comment]
@starchild 
If the issue with key offset not showing is solved, please mark the issue as solved.

**Comment by starchild** [comment]
Yes, colour wave form please.

(Not sure how to mark as solved)

**Comment by kokernutz** [comment]
Color wave form, like the Spectrum one in Mac/PC Traktor?

**Comment by starchild** [comment]
Yes correct, one of the other screen mods has it, so you should be able to just copy that in.

**Comment by kokernutz** [comment]
I am closing this issue as I've opened separate ones for a prefs file and the waveform color.
