### ISSUE TITLE
Key display in the deck header is broken in Traktor 3.2

### ISSUE THREAD

**Issue by jadegraaf** [kokernutz/traktor-kontrol-screens#31]
The key related options for the deck header Info are no longer working. I've tried 17, 18 and 31. The field stays empty. Probably caused by the new key related features?

**Comment by kokernutz** [comment]
OK, thanks for the info. I'll take a look on Monday after I get back from a techno campout. 😎

**Comment by Stefan19782001** [comment]
Hi man, thk a lot for the screen crack but dosen"t work for Tractor pro 3.2 anymore. Can u update the crack pls?

**Comment by jadegraaf** [comment]
> Hi man, thk a lot for the screen crack but dosen"t work for Tractor pro 3.2 anymore. Can u update the crack pls?

Did you reinstall qml directory? With every Traktor update the modification is removed.

**Comment by Stefan19782001** [comment]
Hi but this qml folder is working for traktor3.1?
i will send mesage here with the answer.

**Comment by Stefan19782001** [comment]
is it working . thank and aslo PLEASE in browser mode from display why i cant see the key text

**Comment by jadegraaf** [comment]
> is it working . thank and aslo PLEASE in browser mode from display why i cant see the key text

Thats great!

On topic:
the path to propKeyForDisplay was changed from `"app.traktor.decks." + deckId + ".track.key.key_for_display"` to `"app.traktor.decks." + deckId + ".track.key.resulting.quantized"` in Screens/S4MK3/ViewModels/DeckInfo.qml:53

I haven't checked whether this is the cause yet but it seemed relevant, this is the first time I'm taking a peek under the hood myself.

**Comment by Stefan19782001** [comment]
hi my friend ,   did u fix it the issue with key on the browser mode from display?


Stefan

________________________________

**Comment by izakkam** [comment]
In addition to the key field being broken, in the browser, the normally green/yellow/red arrows/circles that indicate key-matching are now showing up as grey rather than colored. Is this intended, or an issue?

**Comment by mpickel** [comment]
Good point, I thought, I did an error in the prefs. 


 Martin Pickel
Leiter EDV
EDV

Sontowski & Partner GmbH
Sebastianstr. 31
91058 Erlangen

Tel: 	+49 9131 7775-32
Fax: 	+49 9131 7775-80

http://www.sontowski.de

Geschäftsführer:
Klaus-Jürgen Sontowski
Dr. Matthias Hubert
Dr. Henrik Medla

Amtsgericht Fürth - HRB 2736

Am 11.07.2019 um 06:47 schrieb izakkam <notifications@github.com>:

In addition to the key field being broken, in the browser, the normally green/yellow/red arrows/circles that indicate key-matching are now showing up as grey rather than colored. Is this intended, or an issue?

**Comment by Stefan19782001** [comment]
hi



the errore key from display . whene i want to change the kay in track is show me  errore.   thank a lots.

________________________________

**Comment by HaryShanthi** [comment]
Hey Guys, 

Is the new qml file for Traktor 3.2 is available? I am not a programmer myself but if there is some changes i need to perform in the installation then kindly advise me accordingly. Thanks for all the effort and my life was made so much easier with this original hack.

**Comment by travisco** [comment]
Any news on a fix for the key issues?

**Comment by Stefan19782001** [comment]
Hi

I send the issue  at display.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bmac16** [comment]
Was the key issue ever resolved?

**Comment by travisco** [comment]
Looks like a code push was done 3 days ago. Try and download it again

**Comment by bmac16** [comment]
Unfortunately, The Key and Key Text still isn't showing on the screen display

**Comment by skymakai** [comment]
Looks like issue is still there.

**Comment by pisicaroz** [comment]
No fix yet ... :(

**Comment by skymakai** [comment]
Looks like ErikMinekus figured it out w/ his mods: https://github.com/ErikMinekus/traktor-kontrol-screens/tree/nexus

**Comment by kokernutz** [comment]
I'm updated my mods to work with Traktor Pro 3.3.

**Comment by bertpatroons** [comment]
> I'm updated my mods to work with Traktor Pro 3.3.

Thanks!!!
