### ISSUE TITLE
Mod not working on 3.2.1

### ISSUE THREAD

**Issue by Doomscalor** [kokernutz/traktor-kontrol-screens#36]
Hey, the mod isn't working on my S8 since updating to 3.2.1. Does anyone know a fix?

**Comment by mpickel** [comment]
unfortunatly I have the same problem

**Comment by mpickel** [comment]
what do you need from us to fix it ?

**Comment by bmac16** [comment]
It's been a few months without an update for 3.2.1.  Is it in the works?

**Comment by kokernutz** [comment]
I won't be updating my mods until 3.3 is released. There are more behind-the-scenes changes in those QML files, and I don't want to do it twice.

**Comment by bmac16** [comment]
Ok. Thanks for letting me know

**Comment by kokernutz** [comment]
I've updated my mods to work with Traktor Pro 3.3.
