### ISSUE TITLE
User preference: waveform colors

### ISSUE THREAD

**Issue by kokernutz** [kokernutz/traktor-kontrol-screens#4]

**Comment by starchild** [comment]
I just copied code from https://gist.github.com/kfigiela/9efcb64f8fa80f9aa7251bc61ca54cdc

I might tweak the colours still, but that's how it's done in anycase. ;)

**Comment by kokernutz** [comment]
This was done and will be in the next release.

**Comment by kokernutz** [comment]
![img_7285](https://user-images.githubusercontent.com/757885/37518645-6739cf40-28ec-11e8-8a3d-90bdd02f80a6.jpg)

**Comment by starchild** [comment]
Awesome.  I can't believe (or maybe I can) that NI left the screens as is.

**Comment by kokernutz** [comment]
I know. It makes me kinda mad/sad.

After using TP3 I have a couple more ideas to bring my mods more in-line with the new TP3 skin.

Stay tuned!

**Comment by starchild** [comment]
Looks good mate. Thanks so much.
