### ISSUE TITLE
Unfortunately nothing changed with screens for my S4MK3 in fresh installed Traktor 3.3.0 108

### ISSUE THREAD

**Issue by dzhidaj** [kokernutz/traktor-kontrol-screens#47]
I've installed fresh Traktor 3.3.0 108, changed CSI Defines and Screens folders and nothing changed to screens of S4MK3. MacOS High Sierra 10.13.6 (17G66)

**Comment by kokernutz** [comment]
There are no changes to the S4 MK3 screens aside from the option to switch to Camelot key.

Is that not working for you?

**Comment by dzhidaj** [comment]
Ok, I understand now it was my misunderstanding.. Thanx for answer anyway.
