### ISSUE TITLE
[Feature Requests] Add Time Column to Browser

### ISSUE THREAD

**Issue by skymakai** [kokernutz/traktor-kontrol-screens#6]
Request to add track time column to Browser.  Is it possible?

**Comment by kokernutz** [comment]
This doesn't appear to be possible at the moment. If you look at ListDelegate.qml, list 13 states the following attributes are available for the tracks:

dataType, nodeIconId, nodeName, nrOfSubnodes, coverUrl, artistName, trackName, bpm, key, keyIndex, rating, loadedInDeck, prevPlayed, prelisten
