### ISSUE TITLE
[Feature Requests] Add Master Tempo Indicator to Track Deck Header

### ISSUE THREAD

**Issue by skymakai** [kokernutz/traktor-kontrol-screens#7]
Request to add an indicator of which deck is the Tempo Master, possibly to the Deck Header.

**Comment by kokernutz** [comment]
I've implemented this. The indicator says MASTER (orange), SYNC (green), or SYNC! (red) when sync is not enabled for the deck.

![img_7223](https://user-images.githubusercontent.com/757885/37246555-3231437c-2479-11e8-8494-309f2573a69d.jpg)

**Comment by skymakai** [comment]
Excellent!  Thanks!  Looking forward to trying it out.

**Comment by kokernutz** [comment]
This was done and will be in the next release. 

![img_7285](https://user-images.githubusercontent.com/757885/37518662-7d3647ce-28ec-11e8-9c9d-5880fa08acdf.jpg)
