### ISSUE TITLE
[Feature Requests] Add Key Lock Indicator to Deck Header

### ISSUE THREAD

**Issue by skymakai** [kokernutz/traktor-kontrol-screens#8]
Request to add an indicator of whether the deck has Key Lock turned on, possibly to the Deck Header.

**Comment by kokernutz** [comment]
OK, I'll get this done for the next release. (Tomorrow?)

**Comment by kokernutz** [comment]
This was completed and will be in the next release.

![img_7285](https://user-images.githubusercontent.com/757885/37518682-937b0434-28ec-11e8-8115-20d148f430c7.jpg)
